  CREATE TABLE "DEMO"."TREES"
   (	"TREE_ID" NUMBER(6,0),
	"TREE_NAME" VARCHAR2(200) COLLATE "USING_NLS_COMP",
	"TREE_STREET" VARCHAR2(500) COLLATE "USING_NLS_COMP",
	"TREE_CITY" VARCHAR2(200) COLLATE "USING_NLS_COMP",
	"TREE_STATE" VARCHAR2(200) COLLATE "USING_NLS_COMP",
	"TREE_ZIP" NUMBER,
	"TREE_DESCRIPTION" VARCHAR2(4000) COLLATE "USING_NLS_COMP",
	"SUBMITTER_NAME" VARCHAR2(500) COLLATE "USING_NLS_COMP",
	"SUBMITTER_EMAIL" VARCHAR2(500) COLLATE "USING_NLS_COMP",
	"SUBMITION_DATE" TIMESTAMP(6),
	"TREE_PICTURE" BLOB
   ) DEFAULT COLLATION "USING_NLS_COMP"  SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"
 LOB ("TREE_PICTURE") STORE AS SECUREFILE  (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES
  STORAGE( INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT));
